formula_e_drivers = {
    "Jean-Éric Vergne": {
        "Nationality": "France",
        "Seasons": "2014–15 – 2023–24",
        "Championship_titles": 2,
        "Entries": 124,
        "Starts": 124,
        "Poles": 16,
        "Wins": 11,
        "Podiums": 35,
        "Fastest_Laps": 6,
        "FanBoosts": 25,
        "Points": 1078
    },
    "Jake Dennis": {
        "Nationality": "United Kingdom",
        "Seasons": "2020–21 – 2023–24",
        "Championship_titles": 1,
        "Entries": 57,
        "Starts": 57,
        "Poles": 6,
        "Wins": 6,
        "Podiums": 21,
        "Fastest_Laps": 9,
        "FanBoosts": 1,
        "Points": 548
    },
    "Stoffel Vandoorne": {
        "Nationality": "Belgium",
        "Seasons": "2018–19 – 2023–24",
        "Championship_titles": 1,
        "Entries": 81,
        "Starts": 81,
        "Poles": 8,
        "Wins": 3,
        "Podiums": 16,
        "Fastest_Laps": 1,
        "FanBoosts": 56,
        "Points": 516
    },
    "Nyck de Vries": {
        "Nationality": "Netherlands",
        "Seasons": "2019–20 – 2021–22, 2023–24",
        "Championship_titles": 1,
        "Entries": 50,
        "Starts": 50,
        "Poles": 2,
        "Wins": 4,
        "Podiums": 8,
        "Fastest_Laps": 3,
        "FanBoosts": 29,
        "Points": 265
    },
    "António Félix da Costa": {
        "Nationality": "Portugal",
        "Seasons": "2014–15 – 2023–24",
        "Championship_titles": 1,
        "Entries": 122,
        "Starts": 122,
        "Poles": 8,
        "Wins": 9,
        "Podiums": 20,
        "Fastest_Laps": 5,
        "FanBoosts": 53,
        "Points": 726
    },
    "Lucas di Grassi": {
        "Nationality": "Brazil",
        "Seasons": "2014–15 – 2023–24",
        "Championship_titles": 1,
        "Entries": 126,
        "Starts": 125,
        "Poles": 4,
        "Wins": 13,
        "Podiums": 40,
        "Fastest_Laps": 11,
        "FanBoosts": 53,
        "Points": 1042
    },
    "Sébastien Buemi": {
        "Nationality": "Switzerland",
        "Seasons": "2014–15 – 2023–24",
        "Championship_titles": 1,
        "Entries": 122,
        "Starts": 121,
        "Poles": 16,
        "Wins": 13,
        "Podiums": 31,
        "Fastest_Laps": 9,
        "FanBoosts": 41,
        "Points": 958
    },
    "Nelson Piquet Jr.": {
        "Nationality": "Brazil",
        "Seasons": "2014–15 – 2018–19",
        "Championship_titles": 1,
        "Entries": 51,
        "Starts": 51,
        "Poles": 1,
        "Wins": 2,
        "Podiums": 5,
        "Fastest_Laps": 4,
        "FanBoosts": 8,
        "Points": 237
    },
    "Oliver Rowland": {
        "Nationality": "United Kingdom",
        "Seasons": "2015–16, 2018–19 – 2023–24",
        "Championship_titles": 0,
        "Entries": 75,
        "Starts": 74,
        "Poles": 8,
        "Wins": 2,
        "Podiums": 12,
        "Fastest_Laps": 3,
        "FanBoosts": 1,
        "Points": 387
    },
    "Mitch Evans": {
        "Nationality": "New Zealand",
        "Seasons": "2016–17 – 2023–24",
        "Championship_titles": 0,
        "Entries": 105,
        "Starts": 105,
        "Poles": 7,
        "Wins": 11,
        "Podiums": 27,
        "Fastest_Laps": 7,
        "FanBoosts": 8,
        "Points": 830
    },
    "Sam Bird": {
        "Nationality": "United Kingdom",
        "Seasons": "2014–15 – 2023–24",
        "Championship_titles": 0,
        "Entries": 122,
        "Starts": 119,
        "Poles": 6,
        "Wins": 12,
        "Podiums": 27,
        "Fastest_Laps": 10,
        "FanBoosts": 14,
        "Points": 875
    },
    "Pascal Wehrlein": {
        "Nationality": "Germany",
        "Seasons": "2018–19 – 2023–24",
        "Championship_titles": 0,
        "Entries": 74,
        "Starts": 74,
        "Poles": 6,
        "Wins": 6,
        "Podiums": 9,
        "Fastest_Laps": 3,
        "FanBoosts": 4,
        "Points": 495
    },
    "Felix Rosenqvist": {
        "Nationality": "Sweden",
        "Seasons": "2016–17 – 2018–19",
        "Championship_titles": 0,
        "Entries": 25,
        "Starts": 25,
        "Poles": 6,
        "Wins": 3,
        "Podiums": 7,
        "Fastest_Laps": 3,
        "FanBoosts": 3,
        "Points": 223
    },
    "Nick Cassidy": {
        "Nationality": "New Zealand",
        "Seasons": "2020–21 – 2023–24",
        "Championship_titles": 0,
        "Entries": 57,
        "Starts": 57,
        "Poles": 5,
        "Wins": 7,
        "Podiums": 19,
        "Fastest_Laps": 5,
        "FanBoosts": 2,
        "Points": 481
    },
    "Edoardo Mortara": {
        "Nationality": "Switzerland",
        "Seasons": "2017–18 – 2023–24",
        "Championship_titles": 0,
        "Entries": 90,
        "Starts": 89,
        "Poles": 3,
        "Wins": 6,
        "Podiums": 13,
        "Fastest_Laps": 2,
        "FanBoosts": 7,
        "Points": 429
    },
    "Nico Prost": {
        "Nationality": "France",
        "Seasons": "2014–15 – 2017–18",
        "Championship_titles": 0,
        "Entries": 45,
        "Starts": 45,
        "Poles": 3,
        "Wins": 3,
        "Podiums": 5,
        "Fastest_Laps": 3,
        "FanBoosts": 0,
        "Points": 304
    },
    "Alexander Sims": {
        "Nationality": "United Kingdom",
        "Seasons": "2018–19 – 2021–22",
        "Championship_titles": 0,
        "Entries": 55,
        "Starts": 55,
        "Poles": 3,
        "Wins": 1,
        "Podiums": 3,
        "Fastest_Laps": 2,
        "FanBoosts": 1,
        "Points": 174
    },
    "Jake Hughes": {
        "Nationality": "United Kingdom",
        "Seasons": "2022–23 – 2023–24",
        "Championship_titles": 0,
        "Entries": 26,
        "Starts": 25,
        "Poles": 3,
        "Wins": 0,
        "Podiums": 0,
        "Fastest_Laps": 0,
        "FanBoosts": 0,
        "Points": 73
    },
        "Maximilian Günther": {
            "Nationality": "Germany",
            "Seasons": ["2018–19", "2023–24"],
            "Championship_titles": 0,
            "Entries": 78,
            "Starts": 77,
            "Poles": 2,
            "Wins": 5,
            "Podiums": 10,
            "Fastest_Laps": 0,
            "FanBoosts": 2,
            "Points": 317
        },
        "Maro Engel": {
            "Nationality": "Germany",
            "Seasons": ["2016–17", "2017–18"],
            "Championship_titles": 0,
            "Entries": 23,
            "Starts": 23,
            "Poles": 0,
            "Wins": 0,
            "Podiums": 0,
            "Fastest_Laps": 0,
            "FanBoosts": 2,
            "Points": 47
        },
        "Jehan Daruvala": {
            "Nationality": "India",
            "Seasons": ["2023-24"],
            "Championship_titles": 0,
            "Entries": 10,
            "Starts": 10,
            "Poles": 0,
            "Wins": 0,
            "Podiums": 0,
            "Fastest_Laps": 0,
            "FanBoosts": 1,
            "Points": "N/A"
        },
        "Jaime Alguersuari": {
            "Nationality": "Spain",
            "Seasons": ["2014–15"],
            "Championship_titles": 0,
            "Entries": 9,
            "Starts": 9,
            "Poles": 0,
            "Wins": 0,
            "Podiums": 0,
            "Fastest_Laps": 0,
            "FanBoosts": 1,
            "Points": 30
        },
        "Takuma Sato": {
            "Nationality": "Japan",
            "Seasons": ["2014–15"],
            "Championship_titles": 0,
            "Entries": 1,
            "Starts": 1,
            "Poles": 0,
            "Wins": 0,
            "Podiums": 0,
            "Fastest_Laps": 0,
            "FanBoosts": 1,
            "Points": 2
        },
        "Antonio Giovinazzi": {
            "Nationality": "Italy",
            "Seasons": ["2021–22"],
            "Championship_titles": 0,
            "Entries": 15,
            "Starts": 15,
            "Poles": 0,
            "Wins": 0,
            "Podiums": 0,
            "Fastest_Laps": 0,
            "FanBoosts": 0,
            "Points": 6
        },
        "Salvador Durán": {
            "Nationality": "Mexico",
            "Seasons": ["2014–15", "2015–16"],
            "Championship_titles": 0,
            "Entries": 13,
            "Starts": 12,
            "Poles": 0,
            "Wins": 0,
            "Podiums": 0,
            "Fastest_Laps": 0,
            "FanBoosts": 0,
            "Points": 13
        },
        "Sérgio Sette Câmara": {
            "Nationality": "Brazil",
            "Seasons": ["2019–20", "2023–24"],
            "Championship_titles": 0,
            "Entries": 63,
            "Starts": 60,
            "Poles": 0,
            "Wins": 0,
            "Podiums": 0,
            "Fastest_Laps": 0,
            "FanBoosts": 0,
            "Points": 43
        },
        "Luca Filippi": {
            "Nationality": "Italy",
            "Seasons": ["2017–18"],
            "Championship_titles": 0,
            "Entries": 11,
            "Starts": 11,
            "Poles": 0,
            "Wins": 0,
            "Podiums": 0,
            "Fastest_Laps": 0,
            "FanBoosts": 0,
            "Points": 1
        },
        "Kamui Kobayashi": {
            "Nationality": "Japan",
            "Seasons": ["2017–18"],
            "Championship_titles": 0,
            "Entries": 2,
            "Starts": 2,
            "Poles": 0,
            "Wins": 0,
            "Podiums": 0,
            "Fastest_Laps": 0,
            "FanBoosts": 0,
            "Points": 0
        },
        "Katherine Legge": {
            "Nationality": "United Kingdom",
            "Seasons": ["2014–15"],
            "Championship_titles": 0,
            "Entries": 2,
            "Starts": 2,
            "Poles": 0,
            "Wins": 0,
            "Podiums": 0,
            "Fastest_Laps": 0,
            "FanBoosts": 0,
            "Points": 0
        },
        "Tom Dillmann": {
            "Nationality": "France",
            "Seasons": ["2016–17", "2018–19"],
            "Championship_titles": 0,
            "Entries": 23,
            "Starts": 23,
            "Poles": 0,
            "Wins": 0,
            "Podiums": 0,
            "Fastest_Laps": 0,
            "FanBoosts": 0,
            "Points": 24
        },
        "Charles Pic": {
            "Nationality": "France",
            "Seasons": ["2014–15"],
            "Championship_titles": 0,
            "Entries": 5,
            "Starts": 5,
            "Poles": 0,
            "Wins": 0,
            "Podiums": 0,
            "Fastest_Laps": 0,
            "FanBoosts": 0,
            "Points": 16
        },
        "Sakon Yamamoto": {
            "Nationality": "Japan",
            "Seasons": ["2014–15"],
            "Championship_titles": 0,
            "Entries": 2,
            "Starts": 2,
            "Poles": 0,
            "Wins": 0,
            "Podiums": 0,
            "Fastest_Laps": 0,
            "FanBoosts": 0,
            "Points": 0
        },
        "Dan Ticktum": {
            "Nationality": "United Kingdom",
            "Seasons": ["2021–22", "2023–24"],
        "Championship_titles": 0,
        "Entries": 42,
        "Starts": 42,
        "Poles": 0,
        "Wins": 0,
        "Podiums": 0,
        "Fastest_Laps": 0,
        "FanBoosts": 0,
        "Points": 41
    },
    "Oliver Askew": {
        "Nationality": "United States",
        "Seasons": ["2021–22"],
        "Championship_titles": 0,
        "Entries": 16,
        "Starts": 16,
        "Poles": 0,
        "Wins": 0,
        "Podiums": 0,
        "Fastest_Laps": 0,
        "FanBoosts": 0,
        "Points": 24
    },
    "Karun Chandhok": {
        "Nationality": "India",
        "Seasons": ["2014–15"],
        "Championship_titles": 0,
        "Entries": 11,
        "Starts": 11,
        "Poles": 0,
        "Wins": 0,
        "Podiums": 0,
        "Fastest_Laps": 0,
        "FanBoosts": 0,
        "Points": 18
    },
    "Pierre Gasly": {
        "Nationality": "France",
        "Seasons": ["2016–17"],
        "Championship_titles": 0,
        "Entries": 2,
        "Starts": 2,
        "Poles": 0,
        "Wins": 0,
        "Podiums": 0,
        "Fastest_Laps": 0,
        "FanBoosts": 0,
        "Points": 18
    },
    "Oriol Servià": {
        "Nationality": "Spain",
        "Seasons": ["2014–15"],
        "Championship_titles": 0,
        "Entries": 4,
        "Starts": 4,
        "Poles": 0,
        "Wins": 0,
        "Podiums": 0,
        "Fastest_Laps": 0,
        "FanBoosts": 0,
        "Points": 16
    },
    "Tom Blomqvist": {
        "Nationality": "United Kingdom",
        "Seasons": ["2017–18", "2019–20", "2020–21"],
        "Championship_titles": 0,
        "Entries": 23,
        "Starts": 23,
        "Poles": 0,
        "Wins": 0,
        "Podiums": 0,
        "Fastest_Laps": 0,
        "FanBoosts": 0,
        "Points": 11
    },
    "James Calado": {
        "Nationality": "United Kingdom",
        "Seasons": ["2019–20"],
        "Championship_titles": 0,
        "Entries": 9,
        "Starts": 9,
        "Poles": 0,
        "Wins": 0,
        "Podiums": 0,
        "Fastest_Laps": 0,
        "FanBoosts": 0,
        "Points": 10
    },
    "Gary Paffett": {
        "Nationality": "United Kingdom",
        "Seasons": ["2018–19"],
        "Championship_titles": 0,
        "Entries": 13,
        "Starts": 13,
        "Poles": 0,
        "Wins": 0,
        "Podiums": 0,
        "Fastest_Laps": 0,
        "FanBoosts": 0,
        "Points": 9
    },
    "Neel Jani": {
        "Nationality": "Switzerland",
        "Seasons": ["2017–18", "2019–20"],
        "Championship_titles": 0,
        "Entries": 13,
        "Starts": 13,
        "Poles": 0,
        "Wins": 0,
        "Podiums": 0,
        "Fastest_Laps": 0,
        "FanBoosts": 0,
        "Points": 8
    },
    "Mike Conway": {
        "Nationality": "United Kingdom",
        "Seasons": ["2015–16", "2016–17"],
        "Championship_titles": 0,
        "Entries": 8,
        "Starts": 8,
        "Poles": 0,
        "Wins": 0,
        "Podiums": 0,
        "Fastest_Laps": 0,
        "FanBoosts": 0,
        "Points": 7
    },
    "Taylor Barnard": {
        "Nationality": "United Kingdom",
        "Seasons": ["2023-24"],
        "Championship_titles": 0,
        "Entries": 3,
        "Starts": 3,
        "Poles": 0,
        "Wins": 0,
        "Podiums": 0,
        "Fastest_Laps": 0,
        "FanBoosts": 0,
        "Points": 5
    },
    "Adam Carroll": {
        "Nationality": "United Kingdom",
        "Seasons": ["2016–17"],
        "Championship_titles": 0,
        "Entries": 12,
        "Starts": 12,
        "Poles": 0,
        "Wins": 0,
        "Podiums": 0,
        "Fastest_Laps": 0,
        "FanBoosts": 0,
        "Points": 5
    },
    "Esteban Gutiérrez": {
        "Nationality": "Mexico",
        "Seasons": ["2016–17"],
        "Championship_titles": 0,
        "Entries": 3,
        "Starts": 3,
        "Poles": 0,
        "Wins": 0,
        "Podiums": 0,
        "Fastest_Laps": 0,
        "FanBoosts": 0,
        "Points": 5
    },
    "Nathanaël Berthon": {
        "Nationality": "France",
        "Seasons": ["2015–16"],
        "Championship_titles": 0,
        "Entries": 3,
        "Starts": 3,
        "Poles": 0,
        "Wins": 0,
        "Podiums": 0,
        "Fastest_Laps": 0,
        "FanBoosts": 0,
        "Points": 4
    },
    "Simona de Silvestro": {
        "Nationality": "Switzerland",
        "Seasons": ["2014–15", "2015–16"],
        "Championship_titles": 0,
        "Entries": 12,
        "Starts": 12,
        "Poles": 0,
        "Wins": 0,
        "Podiums": 0,
        "Fastest_Laps": 0,
        "FanBoosts": 0,
        "Points": 4
    },
        "Joel Eriksson": {
            "Nationality": "Sweden",
            "Seasons": ["2020–21", "2023–24"],
            "Championship_titles": 0,
            "Entries": 10,
            "Starts": 10,
            "Poles": 0,
            "Wins": 0,
            "Podiums": 0,
            "Fastest_Laps": 0,
            "FanBoosts": 0,
            "Points": 3
        },
        "Brendon Hartley": {
            "Nationality": "New Zealand",
            "Seasons": ["2019–20"],
            "Championship_titles": 0,
            "Entries": 5,
            "Starts": 5,
            "Poles": 0,
            "Wins": 0,
            "Podiums": 0,
            "Fastest_Laps": 0,
            "FanBoosts": 0,
            "Points": 2
        },
        "Vitantonio Liuzzi": {
            "Nationality": "Italy",
            "Seasons": ["2014–15", "2015–16"],
            "Championship_titles": 0,
            "Entries": 7,
            "Starts": 5,
            "Poles": 0,
            "Wins": 0,
            "Podiums": 0,
            "Fastest_Laps": 0,
            "FanBoosts": 0,
            "Points": 2
        },
        "Justin Wilson": {
            "Nationality": "United Kingdom",
            "Seasons": ["2014–15"],
            "Championship_titles": 0,
            "Entries": 1,
            "Starts": 1,
            "Poles": 0,
            "Wins": 0,
            "Podiums": 0,
            "Fastest_Laps": 0,
            "FanBoosts": 0,
            "Points": 1
        },
        "Marco Andretti": {
            "Nationality": "United States",
            "Seasons": ["2014–15"],
            "Championship_titles": 0,
            "Entries": 1,
            "Starts": 1,
            "Poles": 0,
            "Wins": 0,
            "Podiums": 0,
            "Fastest_Laps": 0,
            "FanBoosts": 0,
            "Points": 0
        },
        "Paul Aron": {
            "Nationality": "Estonia",
            "Seasons": ["2023–24"],
            "Championship_titles": 0,
            "Entries": 2,
            "Starts": 2,
            "Poles": 0,
            "Wins": 0,
            "Podiums": 0,
            "Fastest_Laps": 0,
            "FanBoosts": 0,
            "Points": 0
        },
        "David Beckmann": {
            "Nationality": "Germany",
            "Seasons": ["2022-23"],
            "Championship_titles": 0,
            "Entries": 2,
            "Starts": 2,
            "Poles": 0,
            "Wins": 0,
            "Podiums": 0,
            "Fastest_Laps": 0,
            "FanBoosts": 0,
            "Points": 0
        },
        "Matthew Brabham": {
            "Nationality": "United States",
            "Seasons": ["2014–15"],
            "Championship_titles": 0,
            "Entries": 2,
            "Starts": 2,
            "Poles": 0,
            "Wins": 0,
            "Podiums": 0,
            "Fastest_Laps": 0,
            "FanBoosts": 0,
            "Points": 0
        },
        "Michela Cerruti": {
            "Nationality": "Italy",
            "Seasons": ["2014–15"],
            "Championship_titles": 0,
            "Entries": 4,
            "Starts": 4,
            "Poles": 0,
            "Wins": 0,
            "Podiums": 0,
            "Fastest_Laps": 0,
            "FanBoosts": 0,
            "Points": 0
        },
        "Alex Fontana": {
            "Nationality": "Switzerland",
            "Seasons": ["2014–15"],
            "Championship_titles": 0,
            "Entries": 2,
            "Starts": 2,
            "Poles": 0,
            "Wins": 0,
            "Podiums": 0,
            "Fastest_Laps": 0,
            "FanBoosts": 0,
            "Points": 0
        },
        "Antonio García": {
            "Nationality": "Spain",
            "Seasons": ["2014–15"],
            "Championship_titles": 0,
            "Entries": 2,
            "Starts": 2,
            "Poles": 0,
            "Wins": 0,
            "Podiums": 0,
            "Fastest_Laps": 0,
            "FanBoosts": 0,
            "Points": 0
        },
        "Jordan King": {
            "Nationality": "United Kingdom",
            "Seasons": ["2023–24"],
            "Championship_titles": 0,
            "Entries": 2,
            "Starts": 2,
            "Poles": 0,
            "Wins": 0,
            "Podiums": 0,
            "Fastest_Laps": 0,
            "FanBoosts": 0,
            "Points": 0
        },
        "Fabio Leimer": {
            "Nationality": "Switzerland",
            "Seasons": ["2014–15"],
            "Championship_titles": 0,
            "Entries": 2,
            "Starts": 2,
            "Poles": 0,
            "Wins": 0,
            "Podiums": 0,
            "Fastest_Laps": 0,
            "FanBoosts": 0,
            "Points": 0
        },
        "Ma Qing Hua": {
            "Nationality": "China",
            "Seasons": ["2015–16", "2017–18", "2019–20"],
            "Championship_titles": 0,
            "Entries": 14,
            "Starts": 14,
            "Poles": 0,
            "Wins": 0,
            "Podiums": 0,
            "Fastest_Laps": 0,
            "FanBoosts": 0,
            "Points": 0
        },
        "Roberto Merhi": {
            "Nationality": "Spain",
            "Seasons": ["2022-23"],
        "Championship_titles": 0,
        "Entries": 7,
        "Starts": 7,
        "Poles": 0,
        "Wins": 0,
        "Podiums": 0,
        "Fastest_Laps": 0,
        "FanBoosts": 0,
        "Points": 0
    },
    "Felipe Nasr": {
        "Nationality": "Brazil",
        "Seasons": ["2018–19"],
        "Championship_titles": 0,
        "Entries": 3,
        "Starts": 3,
        "Poles": 0,
        "Wins": 0,
        "Podiums": 0,
        "Fastest_Laps": 0,
        "FanBoosts": 0,
        "Points": 0
    },
    "Ho-Pin Tung": {
        "Nationality": "China",
        "Seasons": ["2014–15"],
        "Championship_titles": 0,
        "Entries": 3,
        "Starts": 3,
        "Poles": 0,
        "Wins": 0,
        "Podiums": 0,
        "Fastest_Laps": 0,
        "FanBoosts": 0,
        "Points": 0
    },
    "Kelvin van der Linde": {
        "Nationality": "South Africa",
        "Seasons": ["2022–23", "2023–24"],
        "Championship_titles": 0,
        "Entries": 6,
        "Starts": 5,
        "Poles": 0,
        "Wins": 0,
        "Podiums": 0,
        "Fastest_Laps": 0,
        "FanBoosts": 0,
        "Points": 0
    },
    "Jacques Villeneuve": {
        "Nationality": "Canada",
        "Seasons": ["2015–16"],
        "Championship_titles": 0,
        "Entries": 3,
        "Starts": 2,
        "Poles": 0,
        "Wins": 0,
        "Podiums": 0,
        "Fastest_Laps": 0,
        "FanBoosts": 0,
        "Points": 0
    },
        "Jérôme d'Ambrosio": {
            "Nationality": "Belgium",
            "Seasons": ["2014–15", "2015–16", "2016–17", "2017–18", "2018–19", "2019–20"],
            "Championship_titles": 0,
            "Entries": 69,
            "Starts": 68,
            "Poles": 2,
            "Wins": 3,
            "Podiums": 9,
            "Fastest_Laps": 2,
            "FanBoosts": 3,
            "Points": 322
        },
        "Robin Frijns": {
            "Nationality": "Netherlands",
            "Seasons": ["2015–16", "2016–17", "2018–19", "2019–20", "2020–21", "2021–22", "2022–23", "2023–24"],
            "Championship_titles": 0,
            "Entries": 97,
            "Starts": 96,
            "Poles": 2,
            "Wins": 2,
            "Podiums": 14,
            "Fastest_Laps": 4,
            "FanBoosts": 0,
            "Points": 475
        },
        "Daniel Abt": {
            "Nationality": "Germany",
            "Seasons": ["2014–15", "2015–16", "2016–17", "2017–18", "2018–19", "2019–20"],
            "Championship_titles": 0,
            "Entries": 69,
            "Starts": 69,
            "Poles": 2,
            "Wins": 2,
            "Podiums": 10,
            "Fastest_Laps": 7,
            "FanBoosts": 38,
            "Points": 390
        },
        "Alex Lynn": {
            "Nationality": "United Kingdom",
            "Seasons": ["2016–17", "2017–18", "2018–19", "2019–20", "2020–21"],
            "Championship_titles": 0,
            "Entries": 42,
            "Starts": 42,
            "Poles": 2,
            "Wins": 1,
            "Podiums": 3,
            "Fastest_Laps": 0,
            "FanBoosts": 2,
            "Points": 121
        },
        "André Lotterer": {
            "Nationality": "Germany",
            "Seasons": ["2017–18", "2018–19", "2019–20", "2020–21", "2021–22", "2022–23"],
            "Championship_titles": 0,
            "Entries": 81,
            "Starts": 81,
            "Poles": 2,
            "Wins": 0,
            "Podiums": 8,
            "Fastest_Laps": 3,
            "FanBoosts": 8,
            "Points": 363
        },
        "Stéphane Sarrazin": {
            "Nationality": "France",
            "Seasons": ["2014–15", "2015–16", "2016–17", "2017–18"],
            "Championship_titles": 0,
            "Entries": 37,
            "Starts": 37,
            "Poles": 1,
            "Wins": 0,
            "Podiums": 3,
            "Fastest_Laps": 0,
            "FanBoosts": 4,
            "Points": 128
        },
        "Oliver Turvey": {
            "Nationality": "United Kingdom",
            "Seasons": ["2014–15", "2015–16", "2016–17", "2017–18", "2018–19", "2019–20", "2020–21", "2021–22"],
            "Championship_titles": 0,
            "Entries": 90,
            "Starts": 88,
            "Poles": 1,
            "Wins": 0,
            "Podiums": 1,
            "Fastest_Laps": 0,
            "FanBoosts": 4,
            "Points": 113
        },
        "Sacha Fenestraz": {
            "Nationality": "France",
            "Seasons": ["2021–22", "2022–23", "2023–24"],
            "Championship_titles": 0,
            "Entries": 27,
            "Starts": 27,
            "Poles": 1,
            "Wins": 0,
            "Podiums": 0,
            "Fastest_Laps": 0,
            "FanBoosts": 0,
            "Points": 58
        },
        "Jarno Trulli": {
            "Nationality": "Italy",
            "Seasons": ["2014–15", "2015–16"],
            "Championship_titles": 0,
            "Entries": 12,
            "Starts": 11,
            "Poles": 1,
            "Wins": 0,
            "Podiums": 0,
            "Fastest_Laps": 0,
            "FanBoosts": 0,
            "Points": 15
        },
        "Norman Nato": {
            "Nationality": "France",
            "Seasons": ["2020–21", "2021–22", "2022–23", "2023–24"],
            "Championship_titles": 0,
            "Entries": 43,
            "Starts": 43,
            "Poles": 0,
            "Wins": 1,
            "Podiums": 2,
            "Fastest_Laps": 0,
            "FanBoosts": 3,
            "Points": 133
        },
        "Nick Heidfeld": {
            "Nationality": "Germany",
            "Seasons": ["2014–15", "2015–16", "2016–17", "2017–18"],
            "Championship_titles": 0,
            "Entries": 44,
            "Starts": 44,
            "Poles": 0,
            "Wins": 0,
            "Podiums": 8,
            "Fastest_Laps": 1,
            "FanBoosts": 8,
            "Points": 214
        },
        "René Rast": {
            "Nationality": "Germany",
            "Seasons": ["2015–16", "2019–20", "2020–21", "2021–22", "2022–23"],
            "Championship_titles": 0,
            "Entries": 38,
            "Starts": 38,
            "Poles": 0,
            "Wins": 0,
            "Podiums": 3,
            "Fastest_Laps": 3,
            "FanBoosts": 1,
            "Points": 146
    },
    "Loïc Duval": {
        "Nationality": "France",
        "Seasons": ["2014–15", "2015–16", "2016–17"],
        "Championship_titles": 0,
        "Entries": 28,
        "Starts": 28,
        "Poles": 0,
        "Wins": 0,
        "Podiums": 2,
        "Fastest_Laps": 2,
        "FanBoosts": 1,
        "Points": 122
    },
    "José María López": {
        "Nationality": "Argentina",
        "Seasons": ["2016–17", "2017–18", "2018–19"],
        "Championship_titles": 0,
        "Entries": 33,
        "Starts": 33,
        "Poles": 0,
        "Wins": 0,
        "Podiums": 2,
        "Fastest_Laps": 1,
        "FanBoosts": 3,
        "Points": 82
    },
    "Nico Müller": {
        "Nationality": "Switzerland",
        "Seasons": ["2019–20", "2020–21", "2021–22", "2022–23", "2023–24"],
        "Championship_titles": 0,
        "Entries": 42,
        "Starts": 40,
        "Poles": 0,
        "Wins": 0,
        "Podiums": 1,
        "Fastest_Laps": 2,
        "FanBoosts": 0,
        "Points": 63
    },
    "Bruno Senna": {
        "Nationality": "Brazil",
        "Seasons": ["2014–15", "2015–16"],
        "Championship_titles": 0,
        "Entries": 21,
        "Starts": 21,
        "Poles": 0,
        "Wins": 0,
        "Podiums": 1,
        "Fastest_Laps": 1,
        "FanBoosts": 4,
        "Points": 90
    },
    "Felipe Massa": {
        "Nationality": "Brazil",
        "Seasons": ["2018–19", "2019–20"],
        "Championship_titles": 0,
        "Entries": 24,
        "Starts": 24,
        "Poles": 0,
        "Wins": 0,
        "Podiums": 1,
        "Fastest_Laps": 0,
        "FanBoosts": 4,
        "Points": 39
    },
    "Franck Montagny": {
        "Nationality": "France",
        "Seasons": ["2014–15"],
        "Championship_titles": 0,
        "Entries": 2,
        "Starts": 2,
        "Poles": 0,
        "Wins": 0,
        "Podiums": 1,
        "Fastest_Laps": 0,
        "FanBoosts": 0,
        "Points": 18
    },
    "Scott Speed": {
        "Nationality": "United States",
        "Seasons": ["2014–15"],
        "Championship_titles": 0,
        "Entries": 4,
        "Starts": 4,
        "Poles": 0,
        "Wins": 0,
        "Podiums": 1,
        "Fastest_Laps": 0,
        "FanBoosts": 0,
        "Points": 18
    }
}

events_data = {
    "CIDADE DO MÉXICO": {"Date": "13 DE JAN.", "Time": "17:00"},
    "DIRIYA I": {"Date": "26 DE JAN.", "Time": "14:00"},
    "DIRIYAH II": {"Date": "27 DE JAN.", "Time": "14:00"},
    "HYDERABAD": {"Date": "CANCELADO", "Time": None},
    "SÃO PAULO": {"Date": "16 DE MAR.", "Time": "14:00"},
    "TÓQUIO": {"Date": "30 DE MAR.", "Time": "03:03"},
    "MISANO I": {"Date": "13 DE ABR.", "Time": "10:03"},
    "MISANO II": {"Date": "14 DE ABR.", "Time": "21:00"},
    "MÔNACO": {"Date": "27 DE ABR.", "Time": "10:03"},
    "BERLIM I": {"Date": "11 DE MAI.", "Time": "10:03"},
    "BERLIM II": {"Date": "12 DE MAI.", "Time": "05:20"},
    "XANGAI I": {"Date": "25 DE MAI.", "Time": "21:00"},
    "XANGAI II": {"Date": "26 DE MAI.", "Time": "21:00"},
    "PORTLAND I": {"Date": "29 DE JUN.", "Time": "21:00"},
    "PORTLAND II": {"Date": "30 DE JUN.", "Time": "21:00"},
    "LONDRES I": {"Date": "20 DE JUL.", "Time": "21:00"},
    "LONDRES II": {"Date": "21 DE JUL.", "Time": "21:00"}
}

participants_data = [
    {"Position": 1, "Name": "Pascal Wehrlein", "Team": "TAG Heuer Porsche Formula E Team", "Points": 198},
    {"Position": 2, "Name": "Mitch Evans", "Team": "Jaguar TCS Racing", "Points": 192},
    {"Position": 3, "Name": "Nick Cassidy", "Team": "Jaguar TCS Racing", "Points": 176},
    {"Position": 4, "Name": "Oliver Rowland", "Team": "Nissan Formula E Team", "Points": 156},
    {"Position": 5, "Name": "Jean-Éric Vergne", "Team": "DS Penske", "Points": 139},
    {"Position": 6, "Name": "António Félix Da Costa", "Team": "TAG Heuer Porsche Formula E Team", "Points": 134},
    {"Position": 7, "Name": "Jake Dennis", "Team": "Andretti Formula E", "Points": 122},
    {"Position": 8, "Name": "Maximilian Günther", "Team": "Maserati MSG Racing", "Points": 73},
    {"Position": 9, "Name": "Robin Frijns", "Team": "Envision Racing", "Points": 66},
    {"Position": 10, "Name": "Stoffel Vandoorne", "Team": "DS Penske", "Points": 61},
    {"Position": 11, "Name": "Sébastien Buemi", "Team": "Envision Racing", "Points": 53},
    {"Position": 12, "Name": "Nico Müller", "Team": "ABT CUPRA Formula E Team", "Points": 52},
    {"Position": 13, "Name": "Sam Bird", "Team": "NEOM McLaren Formula E Team", "Points": 48},
    {"Position": 14, "Name": "Jake Hughes", "Team": "NEOM McLaren Formula E Team", "Points": 48},
    {"Position": 15, "Name": "Norman Nato", "Team": "Andretti Formula E", "Points": 47},
    {"Position": 16, "Name": "Edoardo Mortara", "Team": "Mahindra Racing", "Points": 29},
    {"Position": 17, "Name": "Sacha Fenestraz", "Team": "Nissan Formula E Team", "Points": 26},
    {"Position": 18, "Name": "Nyck De Vries", "Team": "Mahindra Racing", "Points": 18},
    {"Position": 19, "Name": "Dan Ticktum", "Team": "ERT Formula E Team", "Points": 12},
    {"Position": 20, "Name": "Sérgio Sette Câmara", "Team": "ERT Formula E Team", "Points": 11},
    {"Position": 21, "Name": "Jehan Daruvala", "Team": "Maserati MSG Racing", "Points": 8},
    {"Position": 22, "Name": "Taylor Barnard", "Team": "NEOM McLaren Formula E Team", "Points": 5},
    {"Position": 23, "Name": "Lucas Di Grassi", "Team": "ABT CUPRA Formula E Team", "Points": 4},
    {"Position": 24, "Name": "Joel Eriksson", "Team": "Envision Racing", "Points": 2},
    {"Position": 25, "Name": "Kelvin Van der Linde", "Team": "ABT CUPRA Formula E Team", "Points": 0},
    {"Position": 26, "Name": "Jordan King", "Team": "Mahindra Racing", "Points": 0},
    {"Position": 27, "Name": "Paul Aron", "Team": "Envision Racing", "Points": 0},
    {"Position": 28, "Name": "Caio Collet", "Team": "Nissan Formula E Team", "Points": 0}
]



